### PR TITLE
Update to 1.16 and fix 3x gold blessing

### PR DESCRIPTION
**Pull request by Brokkonaut**

### CODE REVIEW

**Comment by Plajer** [comment]
Thanks for the pull request.
I'm not sure if it's as simple as adding 1.16 check to make it work without any problems but I'll take a look at changelog to see if there are no breaking changes.

**Comment by dada513** [comment]
> Thanks for the pull request.
> I'm not sure if it's as simple as adding 1.16 check to make it work without any problems but I'll take a look at changelog to see if there are no breaking changes.

From the 1.16.1 spigot release post:
image

**Comment by Tigerpanzer02** [comment]
First thanks for helping 
Second 1.16 is already added to Dev branch 
Third the other fixes are good

**Comment by Tigerpanzer02** [comment]
its on dev branch 
Thank you

**Pull request closed without merging**
